# Generated by Django 3.0.8 on 2020-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bread',
            name='byo_sandwich',
        ),
        migrations.RemoveField(
            model_name='lettuce',
            name='byo_salad',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='tortilla',
            name='byo_wrap',
        ),
        migrations.AddField(
            model_name='protein',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BYO_Salad',
        ),
        migrations.DeleteModel(
            name='BYO_Sandwich',
        ),
        migrations.DeleteModel(
            name='BYO_Wrap',
        ),
    ]
