# Generated by Django 3.0.8 on 2020-08-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200805_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu_images'),
        ),
    ]
