# Generated by Django 3.0.8 on 2020-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200811_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='salad',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='side',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='soup',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='wrap',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
